AWSTemplateFormatVersion: "2010-09-09"
Description: Assignment EC2 instance with IAM role to access S3

Parameters:

  DataBucketName:
    Type: String
    Default: assignment-bucket-ss

  KeyPairName:
    Type: String
    Default: assignment-key

  InstanceType:
    Type: String
    Default: t3.micro

Resources:

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: assignment-ec2-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  EC2Profile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: assignment-ec2-profile
      Roles:
        - !Ref EC2Role

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Assignment EC2 SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}"
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref EC2Profile
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: assignment-runner
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y python3 python3-pip git
          python3 -m pip install --upgrade pip
          echo "Bootstrap done" > /tmp/bootstrap.log

Outputs:

  InstanceId:
    Value: !Ref EC2Instance

  PublicDNS:
    Value: !GetAtt EC2Instance.PublicDnsName

  SSHCommand:
    Value: !Join
      - ""
      - - "ssh -i "
        - !Ref KeyPairName
        - ".pem ec2-user@"
        - !GetAtt EC2Instance.PublicDnsName